# Generated by Django 3.2.4 on 2021-07-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='chacked',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
